version: '3.5'

services:
  steamdb:
    image: mongo
    ports:
      - "27018:27017"
    networks:
      - proxynet
  steamweb:
    build: .
    command: python3 manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8001:8000"
    depends_on:
      - steamdb
    networks:
      - proxynet

networks:
  proxynet:
    name: GamesBI-network
