# Generated by Django 2.1.1 on 2018-09-06 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.IntegerField(help_text='Id da Steam', primary_key=True, serialize=False, verbose_name='Stream ID')),
                ('name', models.CharField(help_text='Name of game', max_length=100, null=True, verbose_name='Name')),
                ('positive_reviews_steam', models.IntegerField(help_text='Number of positives reviews in the game', null=True, verbose_name='Positives reviews')),
                ('negative_reviews_steam', models.IntegerField(help_text='Number of negatives reviews in the game', null=True, verbose_name='Negatives reviews')),
                ('owners', models.IntegerField(help_text='Number of owners', null=True, verbose_name='Owners')),
                ('average_forever', models.IntegerField(help_text='Average forever of the game', null=True, verbose_name='Average forever')),
                ('average_2weeks', models.IntegerField(help_text='Average forever of the game', null=True, verbose_name='Average 2 weeks')),
                ('price', models.IntegerField(help_text='Price of the game', null=True, verbose_name='Price')),
                ('lenguages', models.CharField(help_text='Languages of the game', max_length=100, null=True, verbose_name='Languages')),
            ],
        ),
    ]
